//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ExportReportingTool.Models.Database
{

    public partial class Reports : XPLiteObject
    {
        Guid fID;
        [Key(true)]
        public Guid ID
        {
            get { return fID; }
            set { SetPropertyValue<Guid>(nameof(ID), ref fID, value); }
        }
        string fName;
        [Size(SizeAttribute.Unlimited)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        string fText;
        [Size(SizeAttribute.Unlimited)]
        public string Text
        {
            get { return fText; }
            set { SetPropertyValue<string>(nameof(Text), ref fText, value); }
        }
    }

}
