//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ExportReportingTool.Models.Database
{
    public static class SprocHelper
    {
        public static DevExpress.Xpo.DB.SelectedData ExecReportHistoryInsert(Session session, Guid ID, string ExportName, DateTime DateTimeOfExport, string UserName, string LocalName)
        {
            return session.ExecuteSproc("ReportHistoryInsert", new OperandValue(ID), new OperandValue(ExportName), new OperandValue(DateTimeOfExport), new OperandValue(UserName), new OperandValue(LocalName));
        }
    }
}
