USE [master]
GO

/****** Object:  Database [LSI_Reporting_Tool]    Script Date: 20.09.2019 23:22:28 ******/
DROP DATABASE [LSI_Reporting_Tool]
GO

/****** Object:  Database [LSI_Reporting_Tool]    Script Date: 20.09.2019 23:22:28 ******/
CREATE DATABASE [LSI_Reporting_Tool]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LSI_Reporting_Tool', FILENAME = N'D:\AA_SQLSERVER\MSSQL14.MSSQLSERVER\MSSQL\DATA\LSI_Reporting_Tool.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LSI_Reporting_Tool_log', FILENAME = N'D:\AA_SQLSERVER\MSSQL14.MSSQLSERVER\MSSQL\DATA\LSI_Reporting_Tool_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [LSI_Reporting_Tool] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LSI_Reporting_Tool].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LSI_Reporting_Tool] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET ARITHABORT OFF 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET  ENABLE_BROKER 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET  MULTI_USER 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LSI_Reporting_Tool] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LSI_Reporting_Tool] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LSI_Reporting_Tool] SET  READ_WRITE 
GO


