//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ReportExportingTool.Module.LSI_Reporting_Tool
{

    public partial class ReportsHistory : XPLiteObject
    {
        Guid fID;
        [Key(true)]
        public Guid ID
        {
            get { return fID; }
            set { SetPropertyValue<Guid>(nameof(ID), ref fID, value); }
        }
        string fExportName;
        [Size(SizeAttribute.Unlimited)]
        public string ExportName
        {
            get { return fExportName; }
            set { SetPropertyValue<string>(nameof(ExportName), ref fExportName, value); }
        }
        DateTime fDateTimeOfExport;
        public DateTime DateTimeOfExport
        {
            get { return fDateTimeOfExport; }
            set { SetPropertyValue<DateTime>(nameof(DateTimeOfExport), ref fDateTimeOfExport, value); }
        }
        string fUserName;
        [Size(SizeAttribute.Unlimited)]
        public string UserName
        {
            get { return fUserName; }
            set { SetPropertyValue<string>(nameof(UserName), ref fUserName, value); }
        }
        string fLocalName;
        [Size(SizeAttribute.Unlimited)]
        public string LocalName
        {
            get { return fLocalName; }
            set { SetPropertyValue<string>(nameof(LocalName), ref fLocalName, value); }
        }
    }

}
